"""
Centralized error codes for PQC Transaction Encryption API
"""

# 🔒 Validation Errors
VALIDATION_ERROR = "VALIDATION_ERROR"

# 🔒 Authentication & Authorization Errors
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"

# 🔒 Encryption Errors
RSA_ENCRYPTION_FAILED = "RSA_ENCRYPTION_FAILED"
PQC_ENCRYPTION_FAILED = "PQC_ENCRYPTION_FAILED"
AES_ENCRYPTION_FAILED = "AES_ENCRYPTION_FAILED"

# 🔒 Decryption Errors
RSA_DECRYPTION_FAILED = "RSA_DECRYPTION_FAILED"
PQC_DECRYPTION_FAILED = "PQC_DECRYPTION_FAILED"
AES_DECRYPTION_FAILED = "AES_DECRYPTION_FAILED"

# 🔒 Database Errors
DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED"
DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED"

# 🔒 Internal Server Error
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# 🔒 Not Found
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

# 🔒 Benchmark Errors
BENCHMARK_FAILED = "BENCHMARK_FAILED"

# ✅ Success Codes (Optional future expansion)
TRANSACTION_ENCRYPTED_SUCCESSFULLY = "TRANSACTION_ENCRYPTED_SUCCESSFULLY"
TRANSACTION_DECRYPTED_SUCCESSFULLY = "TRANSACTION_DECRYPTED_SUCCESSFULLY"
