"""
Centralized error codes for PQC Transaction Encryption API
"""


VALIDATION_ERROR = "VALIDATION_ERROR"


AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"


RSA_ENCRYPTION_FAILED = "RSA_ENCRYPTION_FAILED"
PQC_ENCRYPTION_FAILED = "PQC_ENCRYPTION_FAILED"
AES_ENCRYPTION_FAILED = "AES_ENCRYPTION_FAILED"


RSA_DECRYPTION_FAILED = "RSA_DECRYPTION_FAILED"
PQC_DECRYPTION_FAILED = "PQC_DECRYPTION_FAILED"
AES_DECRYPTION_FAILED = "AES_DECRYPTION_FAILED"

DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED"
DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED"


INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"


BENCHMARK_FAILED = "BENCHMARK_FAILED"


TRANSACTION_ENCRYPTED_SUCCESSFULLY = "TRANSACTION_ENCRYPTED_SUCCESSFULLY"
TRANSACTION_DECRYPTED_SUCCESSFULLY = "TRANSACTION_DECRYPTED_SUCCESSFULLY"
