apiVersion: apps/v1
kind: Deployment
metadata:
  name: pqc-encryption-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pqc-encryption
  template:
    metadata:
      labels:
        app: pqc-encryption
    spec:
      containers:
      - name: pqc-encryption
        image: us-central1-docker.pkg.dev/PROJECT_ID/REPO_NAME/pqc-encryption:latest
        ports:
        - containerPort: 8000
      imagePullPolicy: Always
